/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panneauEdition;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import src.EtatPrepaFarine;
import simulation.SimulateurPrepaFarine;
import src.formattageChamps.FormateurNombre;

/**
 *
 * @author MoubarakZoure
 */
public class VecteurEtatPreparerFarine extends javax.swing.JPanel implements PaneFieldsChecker {

    private SimulateurPrepaFarine simlateur = new SimulateurPrepaFarine();

    /**
     * Creates new form VecteurEtatPreparerFarine
     */
    public VecteurEtatPreparerFarine() {
        initComponents();
        allowOnlyNumbers();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        o2c_fld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        coc_fld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        a50t1_fld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        a50p1_fld = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        a52t1_fld = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        a52p2_fld = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        a53t1_fld = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        a53t2__fld = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        a53p1_fld = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        a54t1_fld = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        a54t2_fld = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        a54p2_fld = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel1.setText("Teneur O2 A50");

        o2c_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel2.setText("Teneur CO A50");

        coc_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel3.setText("Temp sortie gaz A50");

        a50t1_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        a50t1_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a50t1_fldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel4.setText("Pression sortie A50");

        a50p1_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel5.setText("Temp gaz  sortie A52");

        a52t1_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel6.setText("Pression A52");

        a52p2_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel7.setText("Temp gaz A53");

        a53t1_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel8.setText("Temp matiere A53");

        a53t2__fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel9.setText("Pression A53");

        a53p1_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel10.setText("Temp gaz A54");

        a54t1_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel11.setText("Temp matiere A54");

        a54t2_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel12.setText("Pression A54");

        a54p2_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(o2c_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(a50p1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a50t1_fld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(coc_fld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a52t1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(a52p2_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(a53t2__fld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a53t1_fld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a53p1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(a54t1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(a54p2_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a54t2_fld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a54t1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a54t2_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a54p2_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(a52t1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a53p1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a52p2_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a53t1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a53t2__fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(o2c_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coc_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a50t1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a50p1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public EtatPrepaFarine extractStateVector() {

        EtatPrepaFarine etat = new EtatPrepaFarine();
       
        etat.setO2C(Double.parseDouble(o2c_fld.getText()));
        etat.setCOC(Double.parseDouble(coc_fld.getText()));
        etat.setA50T1(Double.parseDouble(a50t1_fld.getText()));
        etat.setA50P1(Double.parseDouble(a50p1_fld.getText()));
        etat.setA52T1(Double.parseDouble(a52t1_fld.getText()));
        etat.setA52P2(Double.parseDouble(a52p2_fld.getText()));
        etat.setA53T1(Double.parseDouble(a53t1_fld.getName()));
        etat.setA53T2(Double.parseDouble(a53t2__fld.getText()));
        etat.setA53P1(Double.parseDouble(a53p1_fld.getText()));
        etat.setA54T1(Double.parseDouble(a54t1_fld.getText()));
        etat.setA54T2(Double.parseDouble(a54t2_fld.getText()));
        etat.setA54P2(Double.parseDouble(a54p2_fld.getText()));
        
        etat.setX_O2C(0);
        etat.setX_COC(simlateur.getX_COC());
        etat.setX_A50T1(simlateur.getX_A50T1());
        etat.setX_A50P1(0);
        etat.setX_A52T1(simlateur.getX_A52T1());
        etat.setX_A52P2(simlateur.getX_A52P2());
        etat.setX_A53T1(simlateur.getX_A53T1());
        etat.setX_A53T2(simlateur.getX_A53T2());
        etat.setX_A53P1(0);
        etat.setX_A54T1(simlateur.getX_A54T1());
        etat.setX_A54T2(simlateur.getX_A54T2());
        etat.setX_A54P2(0);

        return etat;
    }


    private void a50t1_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a50t1_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a50t1_fldActionPerformed

    public boolean isOneFieldEmpty(JTextField[] textFields) {
        for (JTextField field : textFields) {
            if (field.getText().equals("")) {
                return true;
            }
        }

        return false;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a50p1_fld;
    private javax.swing.JTextField a50t1_fld;
    private javax.swing.JTextField a52p2_fld;
    private javax.swing.JTextField a52t1_fld;
    private javax.swing.JTextField a53p1_fld;
    private javax.swing.JTextField a53t1_fld;
    private javax.swing.JTextField a53t2__fld;
    private javax.swing.JTextField a54p2_fld;
    private javax.swing.JTextField a54t1_fld;
    private javax.swing.JTextField a54t2_fld;
    private javax.swing.JTextField coc_fld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField o2c_fld;
    // End of variables declaration//GEN-END:variables

    @Override
    public void allowOnlyNumbers() {
        JTextField[] textFields = {o2c_fld, a50p1_fld, a50t1_fld, a52p2_fld, a52t1_fld, a53p1_fld, a53t1_fld,
            a53t2__fld, a54p2_fld, a54t1_fld, a54t2_fld, coc_fld};
        for (JTextField field : textFields) {
            new FormateurNombre().formatter(field);

        }

    }

    @Override
    public void checkAllFieldIsEdited(JFrame context) { // permet de savoir s'il n'ya pas des champs vides
        JTextField[] textFields = {o2c_fld, a50p1_fld, a50t1_fld, a52p2_fld, a52t1_fld, a53p1_fld, a53t1_fld,
            a53t2__fld, a54p2_fld, a54t1_fld, a54t2_fld, coc_fld};
        if (isOneFieldEmpty(textFields)) {
            JOptionPane.showMessageDialog(context, PaneFieldsChecker.emptyFld_msg, PaneFieldsChecker.emptyFld_title, JOptionPane.INFORMATION_MESSAGE);
        }

    }
}
