/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

/**
 *
 * @author MoubarakZoure
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        function_slt2 = new javax.swing.JComboBox();
        component_slt2 = new javax.swing.JComboBox();
        defaillance_slt2 = new javax.swing.JComboBox();
        vecteur_etat_pne = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel8.setFont(new java.awt.Font("Yu Mincho", 0, 18)); // NOI18N
        jLabel8.setText("Défaillance ");

        jLabel9.setFont(new java.awt.Font("Yu Mincho", 0, 18)); // NOI18N
        jLabel9.setText("Composant  ");

        jLabel10.setFont(new java.awt.Font("Yu Mincho", 0, 18)); // NOI18N
        jLabel10.setText("Fonction           ");

        function_slt2.setFont(new java.awt.Font("Yu Mincho", 0, 18)); // NOI18N
        function_slt2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Préparer la farine crue" }));
        function_slt2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                function_slt2ItemStateChanged(evt);
            }
        });

        component_slt2.setFont(new java.awt.Font("Yu Mincho", 0, 18)); // NOI18N
        component_slt2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Préchauffeur à cyclone", "Boite à fumée", "Four" }));
        component_slt2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                component_slt2ItemStateChanged(evt);
            }
        });
        component_slt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                component_slt2ActionPerformed(evt);
            }
        });

        defaillance_slt2.setFont(new java.awt.Font("Yu Mincho", 0, 18)); // NOI18N
        defaillance_slt2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Marche perturbé", "************", " ", " " }));
        defaillance_slt2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                defaillance_slt2ItemStateChanged(evt);
            }
        });
        defaillance_slt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaillance_slt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(component_slt2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(defaillance_slt2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(function_slt2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(component_slt2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(function_slt2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaillance_slt2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        vecteur_etat_pne.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout vecteur_etat_pneLayout = new javax.swing.GroupLayout(vecteur_etat_pne);
        vecteur_etat_pne.setLayout(vecteur_etat_pneLayout);
        vecteur_etat_pneLayout.setHorizontalGroup(
            vecteur_etat_pneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        vecteur_etat_pneLayout.setVerticalGroup(
            vecteur_etat_pneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("TITUS Cyberbit Basic", 0, 18)); // NOI18N
        jButton1.setText("Diagnostiquer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vecteur_etat_pne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vecteur_etat_pne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void function_slt2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_function_slt2ItemStateChanged

        String selected_function=function_slt.getSelectedItem().toString();
        String[] his_defs=fonction_defaillance.get(selected_function);
        defaillance_slt.setModel(new DefaultComboBoxModel(his_defs));
    }//GEN-LAST:event_function_slt2ItemStateChanged

    private void component_slt2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_component_slt2ItemStateChanged
        String selected_comp=component_slt.getSelectedItem().toString();
        String[] his_functions=composant_fonction.get(selected_comp);// his = composant
        String his_first_function=his_functions[0];
        String[] first_function_defs=fonction_defaillance.get(his_first_function); // his = first function
        function_slt.setModel(new DefaultComboBoxModel(his_functions));
        defaillance_slt.setModel(new DefaultComboBoxModel(first_function_defs));
        etatPaneSelection();
    }//GEN-LAST:event_component_slt2ItemStateChanged

    private void component_slt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_component_slt2ActionPerformed

    }//GEN-LAST:event_component_slt2ActionPerformed

    private void defaillance_slt2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_defaillance_slt2ItemStateChanged
        etatPaneSelection();
    }//GEN-LAST:event_defaillance_slt2ItemStateChanged

    private void defaillance_slt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaillance_slt2ActionPerformed

    }//GEN-LAST:event_defaillance_slt2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox component_slt;
    private javax.swing.JComboBox component_slt1;
    private javax.swing.JComboBox component_slt2;
    private javax.swing.JComboBox defaillance_slt;
    private javax.swing.JComboBox defaillance_slt1;
    private javax.swing.JComboBox defaillance_slt2;
    private javax.swing.JComboBox function_slt;
    private javax.swing.JComboBox function_slt1;
    private javax.swing.JComboBox function_slt2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel vecteur_etat_pne;
    // End of variables declaration//GEN-END:variables
}
