/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panneauEdition;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import src.EtatCalcination;
import simulation.SimulateurCalcination;
import controlChamp.FormateurNombre;

/**
 *
 * @author MoubarakZoure
 */
public class VecteurEtatCalcination extends javax.swing.JPanel implements PaneFieldsChecker {
    
    SimulateurCalcination simulateur=new SimulateurCalcination();

    /**
     * Creates new form VecteurEtatPreparerFarine
     */
    public VecteurEtatCalcination() {
        initComponents();
        simulateur.startSimulation();
        allowOnlyNumbers();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        o2f_fld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        w01p3_fld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        w01p1_fld = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        w01t1_fld = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        v31f1_fld = new javax.swing.JTextField();
        cop_fld = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel1.setText("Teneur O2 boite à fumée");

        o2f_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel2.setText("Teneur CO boit à fumée");

        w01p3_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel3.setText("Pression  Sortie boite à fumée");

        jLabel4.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel4.setText("Pression Entrée boite à fumée");

        w01p1_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel5.setText("Temp gaz Entrée boite à fumée");

        w01t1_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N
        jLabel6.setText("Débit gaz");

        v31f1_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        cop_fld.setFont(new java.awt.Font("Yu Mincho", 0, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(o2f_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cop_fld))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(w01p3_fld)))
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(w01t1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(w01p1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(v31f1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o2f_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(w01p1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(w01t1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cop_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(v31f1_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(w01p3_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public EtatCalcination extractStateVector() {

        EtatCalcination etat = new EtatCalcination();

        etat.setO2F(Double.parseDouble(o2f_fld.getText()));
        etat.setCOP(Double.parseDouble(cop_fld.getText()));
        etat.setW01P3(Double.parseDouble(w01p3_fld.getText()));
        etat.setW01P1(Double.parseDouble(w01p1_fld.getText()));
        etat.setW01T1(Double.parseDouble(w01t1_fld.getText()));
        etat.setV31F1(Double.parseDouble(v31f1_fld.getText()));
        
        etat.setX_O2F(0);
        etat.setX_COP(simulateur.getX_COP());
        etat.setX_W01P3(0);
        etat.setX_W01P1(0);
        etat.setX_W01T1(simulateur.getX_W01T1());
        etat.setX_V31F1(0);
        System.out.println(etat.toString());
        return etat;
    }

    public boolean isOneFieldEmpty(JTextField[] textFields) {
        for (JTextField field : textFields) {
            if (field.getText().equals("")) {
                return true;
            }
        }

        return false;

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cop_fld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField o2f_fld;
    private javax.swing.JTextField v31f1_fld;
    private javax.swing.JTextField w01p1_fld;
    private javax.swing.JTextField w01p3_fld;
    private javax.swing.JTextField w01t1_fld;
    // End of variables declaration//GEN-END:variables

    @Override
    public void checkAllFieldIsEdited(JFrame context) {
        JTextField[] textFields = {cop_fld, o2f_fld, v31f1_fld, w01p1_fld, w01p3_fld, w01t1_fld};
        if (isOneFieldEmpty(textFields)) {
            JOptionPane.showMessageDialog(context, PaneFieldsChecker.emptyFld_msg, PaneFieldsChecker.emptyFld_title, JOptionPane.INFORMATION_MESSAGE);
        }
    }

    @Override
    public void allowOnlyNumbers() {
        JTextField[] textFields = {cop_fld, o2f_fld, v31f1_fld, w01p1_fld, w01p3_fld, w01t1_fld};
        for (JTextField field : textFields) {
            new FormateurNombre().formatter(field);

        }

    }
}
